### ISSUE TITLE
Conflict With Chains-Link

### ISSUE THREAD

**Issue by Avakining** [Spaceman/FabricSecretRooms#3]
Crash on start-up when installed alongside [Chains-Link](https://www.curseforge.com/minecraft/mc-mods/chains-link)

Full Log: [https://paste.ee/p/OxBIo](https://paste.ee/p/OxBIo)

Crash Report: [https://paste.ee/p/9nMOY](https://paste.ee/p/9nMOY)

**Comment by Spaceman** [comment]
I think this might have been resolved on Chains-Link's side but I'm not sure ill do some testing
