### ISSUE TITLE
hwyla output feature request/suggestion

### ISSUE THREAD

**Issue by superon** [Spaceman/FabricSecretRooms#5]
could you make it so hwyla outputs what the blocks appear to be when viewed from that particular side?
that would be great

**Comment by Spaceman** [comment]
I would love to do this but it would require a hacky solution that I don't feel really fits well into the mod

**Comment by superon** [comment]
when i wrote this i was thinking specifically about secret rooms mod, the blocks being instantly revealed by hwyla and other such tools doesn't fit with the nature of "Secret", i now see that i didn't state that in the request so state it here incase it wasn't previously obvious and reasoning remained obscured.

**Comment by Spaceman** [comment]
Yeah I get what you mean but in order to do that it would be rather Hacky as I would have to implement a mixin on top of the HWYALA code that only runs when HWYALA is installed and every time HWYALA updates the mixin would break

**Comment by ashyashton** [comment]
I know this is like a year old but I was looking for this exact feature as well so I figure I'll toss my two cents in anyways: Do you think it may work better if you were to instead add a secondary add-on with the aforementioned mixin? Then the mod with the mixin would break when HWYLA updates, but the base mod wouldn't. Then you could just update the mixin mod separately, and people who don't have HWYLA don't have that code clogging things up. You wouldn't have to code anything that only runs when HWYLA is active, it would just be automatic.

Just a suggestion I wanted to toss out there, in case you wanted to consider it!
